image: docker

services:
  - docker:dind

js:
  type: test
  script:
    - docker build -t minirun-refactoring-js:latest ./js/
    - docker run minirun-refactoring-js:latest npm run test

ruby:
  type: test
  script:
    - docker build -t minirun-refactoring-ruby:latest ./ruby/
    - docker run minirun-refactoring-ruby:latest bundle exec rspec

php:
  type: test
  script:
    - docker build -t minirun-refactoring-php:latest ./php/
    - docker run minirun-refactoring-php:latest bin/phpunit test
