#!/bin/sh

docker build -t minirun-refactoring-js:latest .

echo ""
echo "This command opens a node console. To load your code run:"
echo "    .load src/Checkout.js"
echo "To quit, run:"
echo "    .exit"
echo ""

docker run --rm -it minirun-refactoring-js:latest
